<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.01">
    <pacs.008.001.01>
        <GrpHdr>
            <MsgId></MsgId>
            <CreDtTm></CreDtTm>
            <BtchBookg></BtchBookg>
            <NbOfTxs></NbOfTxs>
            <CtrlSum></CtrlSum>
            <TtlIntrBkSttlmAmt Ccy="EUR"></TtlIntrBkSttlmAmt>
            <IntrBkSttlmDt></IntrBkSttlmDt>
            <SttlmInf>
                <SttlmMtd></SttlmMtd>
                <SttlmAcct>
                    <Id>
                          <IBAN></IBAN>
                    </Id>
                    <Tp>
                          <Cd></Cd>
                    </Tp>
                    <Ccy></Ccy>
                    <Nm></Nm>
                </SttlmAcct>
                <ClrSys>
                      <ClrSysId></ClrSysId>
                </ClrSys>
                <InstgRmbrsmntAgt>
                    <FinInstnId>
                          <BIC></BIC>
                    </FinInstnId>
                    <BrnchId>
                        <Id></Id>
                        <Nm></Nm>
                        <PstlAdr>
                            <AdrTp></AdrTp>
                            <AdrLine></AdrLine>
                            <StrtNm></StrtNm>
                            <BldgNb></BldgNb>
                            <PstCd></PstCd>
                            <TwnNm></TwnNm>
                            <CtrySubDvsn></CtrySubDvsn>
                            <Ctry></Ctry>
                        </PstlAdr>
                    </BrnchId>
                </InstgRmbrsmntAgt>
                <InstgRmbrsmntAgtAcct>
                    <Id>
                          <IBAN></IBAN>
                    </Id>
                    <Tp>
                          <Cd></Cd>
                    </Tp>
                    <Ccy></Ccy>
                    <Nm></Nm>
                </InstgRmbrsmntAgtAcct>
                <InstdRmbrsmntAgt>
                    <FinInstnId>
                          <BIC></BIC>
                    </FinInstnId>
                    <BrnchId>
                        <Id></Id>
                        <Nm></Nm>
                        <PstlAdr>
                            <AdrTp></AdrTp>
                            <AdrLine></AdrLine>
                            <StrtNm></StrtNm>
                            <BldgNb></BldgNb>
                            <PstCd></PstCd>
                            <TwnNm></TwnNm>
                            <CtrySubDvsn></CtrySubDvsn>
                            <Ctry></Ctry>
                        </PstlAdr>
                    </BrnchId>
                </InstdRmbrsmntAgt>
                <InstdRmbrsmntAgtAcct>
                    <Id>
                          <IBAN></IBAN>
                    </Id>
                    <Tp>
                          <Cd></Cd>
                    </Tp>
                    <Ccy></Ccy>
                    <Nm></Nm>
                </InstdRmbrsmntAgtAcct>
                <ThrdRmbrsmntAgt>
                    <FinInstnId>
                          <BIC></BIC>
                    </FinInstnId>
                    <BrnchId>
                        <Id></Id>
                        <Nm></Nm>
                        <PstlAdr>
                            <AdrTp></AdrTp>
                            <AdrLine></AdrLine>
                            <StrtNm></StrtNm>
                            <BldgNb></BldgNb>
                            <PstCd></PstCd>
                            <TwnNm></TwnNm>
                            <CtrySubDvsn></CtrySubDvsn>
                            <Ctry></Ctry>
                        </PstlAdr>
                    </BrnchId>
                </ThrdRmbrsmntAgt>
                <ThrdRmbrsmntAgtAcct>
                    <Id>
                          <IBAN></IBAN>
                    </Id>
                    <Tp>
                          <Cd></Cd>
                    </Tp>
                    <Ccy></Ccy>
                    <Nm></Nm>
                </ThrdRmbrsmntAgtAcct>
            </SttlmInf>
            <PmtTpInf>
                <InstrPrty></InstrPrty>
                  <SvcLvl>
                        <Cd></Cd>
                  </SvcLvl>
                <LclInstrm>
                      <Cd></Cd>
                </LclInstrm>
                <CtgyPurp></CtgyPurp>
            </PmtTpInf>
            <InstgAgt>
                <FinInstnId>
                      <BIC></BIC>
                </FinInstnId>
                <BrnchId>
                    <Id></Id>
                    <Nm></Nm>
                    <PstlAdr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </PstlAdr>
                </BrnchId>
            </InstgAgt>
            <InstdAgt>
                <FinInstnId>
                      <BIC></BIC>
                </FinInstnId>
                <BrnchId>
                    <Id></Id>
                    <Nm></Nm>
                    <PstlAdr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </PstlAdr>
                </BrnchId>
            </InstdAgt>
        </GrpHdr>
        <CdtTrfTxInf>
            <PmtId>
                <InstrId></InstrId>
                <EndToEndId></EndToEndId>
                <TxId></TxId>
            </PmtId>
            <PmtTpInf>
                <InstrPrty></InstrPrty>
                  <SvcLvl>
                        <Cd></Cd>
                  </SvcLvl>
                <LclInstrm>
                      <Cd></Cd>
                </LclInstrm>
                <CtgyPurp></CtgyPurp>
            </PmtTpInf>
            <IntrBkSttlmAmt Ccy="EUR"></IntrBkSttlmAmt>
            <IntrBkSttlmDt></IntrBkSttlmDt>
            <SttlmTmIndctn>
                <DbtDtTm></DbtDtTm>
                <CdtDtTm></CdtDtTm>
            </SttlmTmIndctn>
            <SttlmTmReq>
                <CLSTm></CLSTm>
            </SttlmTmReq>
            <AccptncDtTm></AccptncDtTm>
            <PoolgAdjstmntDt></PoolgAdjstmntDt>
            <InstdAmt Ccy="EUR"></InstdAmt>
            <XchgRate></XchgRate>
            <ChrgBr></ChrgBr>
            <ChrgsInf>
                <ChrgsAmt Ccy="EUR"></ChrgsAmt>
                <ChrgsPty>
                    <FinInstnId>
                          <BIC></BIC>
                    </FinInstnId>
                    <BrnchId>
                        <Id></Id>
                        <Nm></Nm>
                        <PstlAdr>
                            <AdrTp></AdrTp>
                            <AdrLine></AdrLine>
                            <StrtNm></StrtNm>
                            <BldgNb></BldgNb>
                            <PstCd></PstCd>
                            <TwnNm></TwnNm>
                            <CtrySubDvsn></CtrySubDvsn>
                            <Ctry></Ctry>
                        </PstlAdr>
                    </BrnchId>
                </ChrgsPty>
            </ChrgsInf>
            <PrvsInstgAgt>
                <FinInstnId>
                      <BIC></BIC>
                </FinInstnId>
                <BrnchId>
                    <Id></Id>
                    <Nm></Nm>
                    <PstlAdr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </PstlAdr>
                </BrnchId>
            </PrvsInstgAgt>
            <PrvsInstgAgtAcct>
                <Id>
                      <IBAN></IBAN>
                </Id>
                <Tp>
                      <Cd></Cd>
                </Tp>
                <Ccy></Ccy>
                <Nm></Nm>
            </PrvsInstgAgtAcct>
            <InstgAgt>
                <FinInstnId>
                      <BIC></BIC>
                </FinInstnId>
                <BrnchId>
                    <Id></Id>
                    <Nm></Nm>
                    <PstlAdr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </PstlAdr>
                </BrnchId>
            </InstgAgt>
            <InstdAgt>
                <FinInstnId>
                      <BIC></BIC>
                </FinInstnId>
                <BrnchId>
                    <Id></Id>
                    <Nm></Nm>
                    <PstlAdr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </PstlAdr>
                </BrnchId>
            </InstdAgt>
            <IntrmyAgt1>
                <FinInstnId>
                      <BIC></BIC>
                </FinInstnId>
                <BrnchId>
                    <Id></Id>
                    <Nm></Nm>
                    <PstlAdr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </PstlAdr>
                </BrnchId>
            </IntrmyAgt1>
            <IntrmyAgt1Acct>
                <Id>
                      <IBAN></IBAN>
                </Id>
                <Tp>
                      <Cd></Cd>
                </Tp>
                <Ccy></Ccy>
                <Nm></Nm>
            </IntrmyAgt1Acct>
            <IntrmyAgt2>
                <FinInstnId>
                      <BIC></BIC>
                </FinInstnId>
                <BrnchId>
                    <Id></Id>
                    <Nm></Nm>
                    <PstlAdr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </PstlAdr>
                </BrnchId>
            </IntrmyAgt2>
            <IntrmyAgt2Acct>
                <Id>
                      <IBAN></IBAN>
                </Id>
                <Tp>
                      <Cd></Cd>
                </Tp>
                <Ccy></Ccy>
                <Nm></Nm>
            </IntrmyAgt2Acct>
            <IntrmyAgt3>
                <FinInstnId>
                      <BIC></BIC>
                </FinInstnId>
                <BrnchId>
                    <Id></Id>
                    <Nm></Nm>
                    <PstlAdr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </PstlAdr>
                </BrnchId>
            </IntrmyAgt3>
            <IntrmyAgt3Acct>
                <Id>
                      <IBAN></IBAN>
                </Id>
                <Tp>
                      <Cd></Cd>
                </Tp>
                <Ccy></Ccy>
                <Nm></Nm>
            </IntrmyAgt3Acct>
            <UltmtDbtr>
                <Nm></Nm>
                <PstlAdr>
                    <AdrTp></AdrTp>
                    <AdrLine></AdrLine>
                    <StrtNm></StrtNm>
                    <BldgNb></BldgNb>
                    <PstCd></PstCd>
                    <TwnNm></TwnNm>
                    <CtrySubDvsn></CtrySubDvsn>
                    <Ctry></Ctry>
                </PstlAdr>
                <Id>
                      <OrgId>
                          <BIC></BIC>
                          <IBEI></IBEI>
                          <BEI></BEI>
                          <EANGLN></EANGLN>
                          <USCHU></USCHU>
                          <DUNS></DUNS>
                          <BkPtyId></BkPtyId>
                          <TaxIdNb></TaxIdNb>
                          <PrtryId>
                              <Id></Id>
                              <Issr></Issr>
                          </PrtryId>
                      </OrgId>
                </Id>
                <CtryOfRes></CtryOfRes>
            </UltmtDbtr>
            <InitgPty>
                <Nm></Nm>
                <PstlAdr>
                    <AdrTp></AdrTp>
                    <AdrLine></AdrLine>
                    <StrtNm></StrtNm>
                    <BldgNb></BldgNb>
                    <PstCd></PstCd>
                    <TwnNm></TwnNm>
                    <CtrySubDvsn></CtrySubDvsn>
                    <Ctry></Ctry>
                </PstlAdr>
                <Id>
                      <OrgId>
                          <BIC></BIC>
                          <IBEI></IBEI>
                          <BEI></BEI>
                          <EANGLN></EANGLN>
                          <USCHU></USCHU>
                          <DUNS></DUNS>
                          <BkPtyId></BkPtyId>
                          <TaxIdNb></TaxIdNb>
                          <PrtryId>
                              <Id></Id>
                              <Issr></Issr>
                          </PrtryId>
                      </OrgId>
                </Id>
                <CtryOfRes></CtryOfRes>
            </InitgPty>
            <Dbtr>
                <Nm></Nm>
                <PstlAdr>
                    <AdrTp></AdrTp>
                    <AdrLine></AdrLine>
                    <StrtNm></StrtNm>
                    <BldgNb></BldgNb>
                    <PstCd></PstCd>
                    <TwnNm></TwnNm>
                    <CtrySubDvsn></CtrySubDvsn>
                    <Ctry></Ctry>
                </PstlAdr>
                <Id>
                      <OrgId>
                          <BIC></BIC>
                          <IBEI></IBEI>
                          <BEI></BEI>
                          <EANGLN></EANGLN>
                          <USCHU></USCHU>
                          <DUNS></DUNS>
                          <BkPtyId></BkPtyId>
                          <TaxIdNb></TaxIdNb>
                          <PrtryId>
                              <Id></Id>
                              <Issr></Issr>
                          </PrtryId>
                      </OrgId>
                </Id>
                <CtryOfRes></CtryOfRes>
            </Dbtr>
            <DbtrAcct>
                <Id>
                      <IBAN></IBAN>
                </Id>
                <Tp>
                      <Cd></Cd>
                </Tp>
                <Ccy></Ccy>
                <Nm></Nm>
            </DbtrAcct>
            <DbtrAgt>
                <FinInstnId>
                      <BIC></BIC>
                </FinInstnId>
                <BrnchId>
                    <Id></Id>
                    <Nm></Nm>
                    <PstlAdr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </PstlAdr>
                </BrnchId>
            </DbtrAgt>
            <DbtrAgtAcct>
                <Id>
                      <IBAN></IBAN>
                </Id>
                <Tp>
                      <Cd></Cd>
                </Tp>
                <Ccy></Ccy>
                <Nm></Nm>
            </DbtrAgtAcct>
            <CdtrAgt>
                <FinInstnId>
                      <BIC></BIC>
                </FinInstnId>
                <BrnchId>
                    <Id></Id>
                    <Nm></Nm>
                    <PstlAdr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </PstlAdr>
                </BrnchId>
            </CdtrAgt>
            <CdtrAgtAcct>
                <Id>
                      <IBAN></IBAN>
                </Id>
                <Tp>
                      <Cd></Cd>
                </Tp>
                <Ccy></Ccy>
                <Nm></Nm>
            </CdtrAgtAcct>
            <Cdtr>
                <Nm></Nm>
                <PstlAdr>
                    <AdrTp></AdrTp>
                    <AdrLine></AdrLine>
                    <StrtNm></StrtNm>
                    <BldgNb></BldgNb>
                    <PstCd></PstCd>
                    <TwnNm></TwnNm>
                    <CtrySubDvsn></CtrySubDvsn>
                    <Ctry></Ctry>
                </PstlAdr>
                <Id>
                      <OrgId>
                          <BIC></BIC>
                          <IBEI></IBEI>
                          <BEI></BEI>
                          <EANGLN></EANGLN>
                          <USCHU></USCHU>
                          <DUNS></DUNS>
                          <BkPtyId></BkPtyId>
                          <TaxIdNb></TaxIdNb>
                          <PrtryId>
                              <Id></Id>
                              <Issr></Issr>
                          </PrtryId>
                      </OrgId>
                </Id>
                <CtryOfRes></CtryOfRes>
            </Cdtr>
            <CdtrAcct>
                <Id>
                      <IBAN></IBAN>
                </Id>
                <Tp>
                      <Cd></Cd>
                </Tp>
                <Ccy></Ccy>
                <Nm></Nm>
            </CdtrAcct>
            <UltmtCdtr>
                <Nm></Nm>
                <PstlAdr>
                    <AdrTp></AdrTp>
                    <AdrLine></AdrLine>
                    <StrtNm></StrtNm>
                    <BldgNb></BldgNb>
                    <PstCd></PstCd>
                    <TwnNm></TwnNm>
                    <CtrySubDvsn></CtrySubDvsn>
                    <Ctry></Ctry>
                </PstlAdr>
                <Id>
                      <OrgId>
                          <BIC></BIC>
                          <IBEI></IBEI>
                          <BEI></BEI>
                          <EANGLN></EANGLN>
                          <USCHU></USCHU>
                          <DUNS></DUNS>
                          <BkPtyId></BkPtyId>
                          <TaxIdNb></TaxIdNb>
                          <PrtryId>
                              <Id></Id>
                              <Issr></Issr>
                          </PrtryId>
                      </OrgId>
                </Id>
                <CtryOfRes></CtryOfRes>
            </UltmtCdtr>
            <InstrForCdtrAgt>
                <Cd></Cd>
                <InstrInf></InstrInf>
            </InstrForCdtrAgt>
            <InstrForNxtAgt>
                <Cd></Cd>
                <InstrInf></InstrInf>
            </InstrForNxtAgt>
            <Purp>
                  <Cd></Cd>
            </Purp>
            <RgltryRptg>
                <DbtCdtRptgInd></DbtCdtRptgInd>
                <Authrty>
                    <AuthrtyNm></AuthrtyNm>
                    <AuthrtyCtry></AuthrtyCtry>
                </Authrty>
                <RgltryDtls>
                    <Cd></Cd>
                    <Amt Ccy="EUR"></Amt>
                    <Inf></Inf>
                </RgltryDtls>
            </RgltryRptg>
            <RltdRmtInf>
                <RmtId></RmtId>
                <RmtLctnMtd></RmtLctnMtd>
                <RmtLctnElctrncAdr></RmtLctnElctrncAdr>
                <RmtLctnPstlAdr>
                    <Nm></Nm>
                    <Adr>
                        <AdrTp></AdrTp>
                        <AdrLine></AdrLine>
                        <StrtNm></StrtNm>
                        <BldgNb></BldgNb>
                        <PstCd></PstCd>
                        <TwnNm></TwnNm>
                        <CtrySubDvsn></CtrySubDvsn>
                        <Ctry></Ctry>
                    </Adr>
                </RmtLctnPstlAdr>
            </RltdRmtInf>
            <RmtInf>
                <Ustrd></Ustrd>
                <Strd>
                    <RfrdDocInf>
                        <RfrdDocTp>
                              <Cd></Cd>
                            <Issr></Issr>
                        </RfrdDocTp>
                        <RfrdDocNb></RfrdDocNb>
                    </RfrdDocInf>
                    <RfrdDocRltdDt></RfrdDocRltdDt>
                    <RfrdDocAmt>
                          <DuePyblAmt Ccy="EUR"></DuePyblAmt>
                    </RfrdDocAmt>
                    <CdtrRefInf>
                        <CdtrRefTp>
                              <Cd></Cd>
                            <Issr></Issr>
                        </CdtrRefTp>
                        <CdtrRef></CdtrRef>
                    </CdtrRefInf>
                    <Invcr>
                        <Nm></Nm>
                        <PstlAdr>
                            <AdrTp></AdrTp>
                            <AdrLine></AdrLine>
                            <StrtNm></StrtNm>
                            <BldgNb></BldgNb>
                            <PstCd></PstCd>
                            <TwnNm></TwnNm>
                            <CtrySubDvsn></CtrySubDvsn>
                            <Ctry></Ctry>
                        </PstlAdr>
                        <Id>
                              <OrgId>
                                  <BIC></BIC>
                                  <IBEI></IBEI>
                                  <BEI></BEI>
                                  <EANGLN></EANGLN>
                                  <USCHU></USCHU>
                                  <DUNS></DUNS>
                                  <BkPtyId></BkPtyId>
                                  <TaxIdNb></TaxIdNb>
                                  <PrtryId>
                                      <Id></Id>
                                      <Issr></Issr>
                                  </PrtryId>
                              </OrgId>
                        </Id>
                        <CtryOfRes></CtryOfRes>
                    </Invcr>
                    <Invcee>
                        <Nm></Nm>
                        <PstlAdr>
                            <AdrTp></AdrTp>
                            <AdrLine></AdrLine>
                            <StrtNm></StrtNm>
                            <BldgNb></BldgNb>
                            <PstCd></PstCd>
                            <TwnNm></TwnNm>
                            <CtrySubDvsn></CtrySubDvsn>
                            <Ctry></Ctry>
                        </PstlAdr>
                        <Id>
                              <OrgId>
                                  <BIC></BIC>
                                  <IBEI></IBEI>
                                  <BEI></BEI>
                                  <EANGLN></EANGLN>
                                  <USCHU></USCHU>
                                  <DUNS></DUNS>
                                  <BkPtyId></BkPtyId>
                                  <TaxIdNb></TaxIdNb>
                                  <PrtryId>
                                      <Id></Id>
                                      <Issr></Issr>
                                  </PrtryId>
                              </OrgId>
                        </Id>
                        <CtryOfRes></CtryOfRes>
                    </Invcee>
                    <AddtlRmtInf></AddtlRmtInf>
                </Strd>
            </RmtInf>
        </CdtTrfTxInf>
    </pacs.008.001.01>
</Document>


