<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<pn1:Document xmlns:pn1="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02 pain.001.001.02.xsd ">
  <pn1:pain.001.001.02>
    <pn1:GrpHdr>
      <pn1:MsgId>pi1:MsgId</pn1:MsgId>
      <pn1:CreDtTm>2001-12-31T12:00:00</pn1:CreDtTm>
      <pn1:Authstn>pi1:Authstn</pn1:Authstn>
      <pn1:BtchBookg>true</pn1:BtchBookg>
      <pn1:NbOfTxs>pi1:NbOfTxs</pn1:NbOfTxs>
      <pn1:CtrlSum>0.0</pn1:CtrlSum>
      <pn1:Grpg>SNGL</pn1:Grpg>
      <pn1:InitgPty>
        <pn1:Nm>pi1:Nm</pn1:Nm>
        <pn1:PstlAdr>
          <pn1:AdrTp>ADDR</pn1:AdrTp>
          <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
          <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
          <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
          <pn1:PstCd>pi1:PstCd</pn1:PstCd>
          <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
          <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
          <pn1:Ctry>pi1:Ctry</pn1:Ctry>
        </pn1:PstlAdr>
        <pn1:Id>
          <pn1:OrgId>
            <pn1:BIC>pi1:BIC</pn1:BIC>
            <pn1:IBEI>pi1:IBEI</pn1:IBEI>
            <pn1:BEI>pi1:BEI</pn1:BEI>
            <pn1:EANGLN>pi1:EANGLN</pn1:EANGLN>
            <pn1:USCHU>pi1:USCHU</pn1:USCHU>
            <pn1:DUNS>pi1:DUNS</pn1:DUNS>
            <pn1:BkPtyId>pi1:BkPtyId</pn1:BkPtyId>
            <pn1:TaxIdNb>pi1:TaxIdNb</pn1:TaxIdNb>
            <pn1:PrtryId>
              <pn1:Id>pi1:Id</pn1:Id>
              <pn1:Issr>pi1:Issr</pn1:Issr>
            </pn1:PrtryId>
          </pn1:OrgId>
        </pn1:Id>
        <pn1:CtryOfRes>pi1:CtryOfRes</pn1:CtryOfRes>
      </pn1:InitgPty>
      <pn1:FwdgAgt>
        <pn1:FinInstnId>
          <pn1:BIC>pi1:BIC</pn1:BIC>
        </pn1:FinInstnId>
        <pn1:BrnchId>
          <pn1:Id>pi1:Id</pn1:Id>
          <pn1:Nm>pi1:Nm</pn1:Nm>
          <pn1:PstlAdr>
            <pn1:AdrTp>ADDR</pn1:AdrTp>
            <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
            <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
            <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
            <pn1:PstCd>pi1:PstCd</pn1:PstCd>
            <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
            <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
            <pn1:Ctry>pi1:Ctry</pn1:Ctry>
          </pn1:PstlAdr>
        </pn1:BrnchId>
      </pn1:FwdgAgt>
    </pn1:GrpHdr>
    <pn1:PmtInf>
      <pn1:PmtInfId>pi1:PmtInfId</pn1:PmtInfId>
      <pn1:PmtMtd>CHK</pn1:PmtMtd>
      <pn1:PmtTpInf>
        <pn1:InstrPrty>HIGH</pn1:InstrPrty>
        <pn1:SvcLvl>
          <pn1:Cd>SEPA</pn1:Cd>
        </pn1:SvcLvl>
        <pn1:LclInstrm>
          <pn1:Cd>pi1:Cd</pn1:Cd>
        </pn1:LclInstrm>
        <pn1:CtgyPurp>CORT</pn1:CtgyPurp>
      </pn1:PmtTpInf>
      <pn1:ReqdExctnDt>2001-01-01</pn1:ReqdExctnDt>
      <pn1:PoolgAdjstmntDt>2001-01-01</pn1:PoolgAdjstmntDt>
      <pn1:Dbtr>
        <pn1:Nm>pi1:Nm</pn1:Nm>
        <pn1:PstlAdr>
          <pn1:AdrTp>ADDR</pn1:AdrTp>
          <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
          <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
          <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
          <pn1:PstCd>pi1:PstCd</pn1:PstCd>
          <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
          <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
          <pn1:Ctry>pi1:Ctry</pn1:Ctry>
        </pn1:PstlAdr>
        <pn1:Id>
          <pn1:OrgId>
            <pn1:BIC>pi1:BIC</pn1:BIC>
            <pn1:IBEI>pi1:IBEI</pn1:IBEI>
            <pn1:BEI>pi1:BEI</pn1:BEI>
            <pn1:EANGLN>pi1:EANGLN</pn1:EANGLN>
            <pn1:USCHU>pi1:USCHU</pn1:USCHU>
            <pn1:DUNS>pi1:DUNS</pn1:DUNS>
            <pn1:BkPtyId>pi1:BkPtyId</pn1:BkPtyId>
            <pn1:TaxIdNb>pi1:TaxIdNb</pn1:TaxIdNb>
            <pn1:PrtryId>
              <pn1:Id>pi1:Id</pn1:Id>
              <pn1:Issr>pi1:Issr</pn1:Issr>
            </pn1:PrtryId>
          </pn1:OrgId>
        </pn1:Id>
        <pn1:CtryOfRes>pi1:CtryOfRes</pn1:CtryOfRes>
      </pn1:Dbtr>
      <pn1:DbtrAcct>
        <pn1:Id>
          <pn1:IBAN>pi1:IBAN</pn1:IBAN>
        </pn1:Id>
        <pn1:Tp>
          <pn1:Cd>CASH</pn1:Cd>
        </pn1:Tp>
        <pn1:Ccy>pi1:Ccy</pn1:Ccy>
        <pn1:Nm>pi1:Nm</pn1:Nm>
      </pn1:DbtrAcct>
      <pn1:DbtrAgt>
        <pn1:FinInstnId>
          <pn1:BIC>pi1:BIC</pn1:BIC>
        </pn1:FinInstnId>
        <pn1:BrnchId>
          <pn1:Id>pi1:Id</pn1:Id>
          <pn1:Nm>pi1:Nm</pn1:Nm>
          <pn1:PstlAdr>
            <pn1:AdrTp>ADDR</pn1:AdrTp>
            <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
            <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
            <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
            <pn1:PstCd>pi1:PstCd</pn1:PstCd>
            <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
            <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
            <pn1:Ctry>pi1:Ctry</pn1:Ctry>
          </pn1:PstlAdr>
        </pn1:BrnchId>
      </pn1:DbtrAgt>
      <pn1:DbtrAgtAcct>
        <pn1:Id>
          <pn1:IBAN>pi1:IBAN</pn1:IBAN>
        </pn1:Id>
        <pn1:Tp>
          <pn1:Cd>CASH</pn1:Cd>
        </pn1:Tp>
        <pn1:Ccy>pi1:Ccy</pn1:Ccy>
        <pn1:Nm>pi1:Nm</pn1:Nm>
      </pn1:DbtrAgtAcct>
      <pn1:UltmtDbtr>
        <pn1:Nm>pi1:Nm</pn1:Nm>
        <pn1:PstlAdr>
          <pn1:AdrTp>ADDR</pn1:AdrTp>
          <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
          <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
          <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
          <pn1:PstCd>pi1:PstCd</pn1:PstCd>
          <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
          <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
          <pn1:Ctry>pi1:Ctry</pn1:Ctry>
        </pn1:PstlAdr>
        <pn1:Id>
          <pn1:OrgId>
            <pn1:BIC>pi1:BIC</pn1:BIC>
            <pn1:IBEI>pi1:IBEI</pn1:IBEI>
            <pn1:BEI>pi1:BEI</pn1:BEI>
            <pn1:EANGLN>pi1:EANGLN</pn1:EANGLN>
            <pn1:USCHU>pi1:USCHU</pn1:USCHU>
            <pn1:DUNS>pi1:DUNS</pn1:DUNS>
            <pn1:BkPtyId>pi1:BkPtyId</pn1:BkPtyId>
            <pn1:TaxIdNb>pi1:TaxIdNb</pn1:TaxIdNb>
            <pn1:PrtryId>
              <pn1:Id>pi1:Id</pn1:Id>
              <pn1:Issr>pi1:Issr</pn1:Issr>
            </pn1:PrtryId>
          </pn1:OrgId>
        </pn1:Id>
        <pn1:CtryOfRes>pi1:CtryOfRes</pn1:CtryOfRes>
      </pn1:UltmtDbtr>
      <pn1:ChrgBr>DEBT</pn1:ChrgBr>
      <pn1:ChrgsAcct>
        <pn1:Id>
          <pn1:IBAN>pi1:IBAN</pn1:IBAN>
        </pn1:Id>
        <pn1:Tp>
          <pn1:Cd>CASH</pn1:Cd>
        </pn1:Tp>
        <pn1:Ccy>pi1:Ccy</pn1:Ccy>
        <pn1:Nm>pi1:Nm</pn1:Nm>
      </pn1:ChrgsAcct>
      <pn1:ChrgsAcctAgt>
        <pn1:FinInstnId>
          <pn1:BIC>pi1:BIC</pn1:BIC>
        </pn1:FinInstnId>
        <pn1:BrnchId>
          <pn1:Id>pi1:Id</pn1:Id>
          <pn1:Nm>pi1:Nm</pn1:Nm>
          <pn1:PstlAdr>
            <pn1:AdrTp>ADDR</pn1:AdrTp>
            <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
            <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
            <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
            <pn1:PstCd>pi1:PstCd</pn1:PstCd>
            <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
            <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
            <pn1:Ctry>pi1:Ctry</pn1:Ctry>
          </pn1:PstlAdr>
        </pn1:BrnchId>
      </pn1:ChrgsAcctAgt>
      <pn1:CdtTrfTxInf>
        <pn1:PmtId>
          <pn1:InstrId>pi1:InstrId</pn1:InstrId>
          <pn1:EndToEndId>pi1:EndToEndId</pn1:EndToEndId>
        </pn1:PmtId>
        <pn1:PmtTpInf>
          <pn1:InstrPrty>HIGH</pn1:InstrPrty>
          <pn1:SvcLvl>
            <pn1:Cd>SEPA</pn1:Cd>
          </pn1:SvcLvl>
          <pn1:LclInstrm>
            <pn1:Cd>pi1:Cd</pn1:Cd>
          </pn1:LclInstrm>
          <pn1:CtgyPurp>CORT</pn1:CtgyPurp>
        </pn1:PmtTpInf>
        <pn1:Amt>
          <pn1:InstdAmt Ccy="">0.0</pn1:InstdAmt>
        </pn1:Amt>
        <pn1:XchgRateInf>
          <pn1:XchgRate>0.0</pn1:XchgRate>
          <pn1:RateTp>SPOT</pn1:RateTp>
          <pn1:CtrctId>pi1:CtrctId</pn1:CtrctId>
        </pn1:XchgRateInf>
        <pn1:ChrgBr>DEBT</pn1:ChrgBr>
        <pn1:ChqInstr>
          <pn1:ChqTp>CCHQ</pn1:ChqTp>
          <pn1:ChqNb>pi1:ChqNb</pn1:ChqNb>
          <pn1:ChqFr>
            <pn1:Nm>pi1:Nm</pn1:Nm>
            <pn1:Adr>
              <pn1:AdrTp>ADDR</pn1:AdrTp>
              <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
              <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
              <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
              <pn1:PstCd>pi1:PstCd</pn1:PstCd>
              <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
              <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
              <pn1:Ctry>pi1:Ctry</pn1:Ctry>
            </pn1:Adr>
          </pn1:ChqFr>
          <pn1:DlvryMtd>
            <pn1:Cd>MLDB</pn1:Cd>
          </pn1:DlvryMtd>
          <pn1:DlvrTo>
            <pn1:Nm>pi1:Nm</pn1:Nm>
            <pn1:Adr>
              <pn1:AdrTp>ADDR</pn1:AdrTp>
              <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
              <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
              <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
              <pn1:PstCd>pi1:PstCd</pn1:PstCd>
              <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
              <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
              <pn1:Ctry>pi1:Ctry</pn1:Ctry>
            </pn1:Adr>
          </pn1:DlvrTo>
          <pn1:InstrPrty>HIGH</pn1:InstrPrty>
          <pn1:ChqMtrtyDt>2001-01-01</pn1:ChqMtrtyDt>
          <pn1:FrmsCd>pi1:FrmsCd</pn1:FrmsCd>
          <pn1:MemoFld>pi1:MemoFld</pn1:MemoFld>
          <pn1:RgnlClrZone>pi1:RgnlClrZone</pn1:RgnlClrZone>
          <pn1:PrtLctn>pi1:PrtLctn</pn1:PrtLctn>
        </pn1:ChqInstr>
        <pn1:UltmtDbtr>
          <pn1:Nm>pi1:Nm</pn1:Nm>
          <pn1:PstlAdr>
            <pn1:AdrTp>ADDR</pn1:AdrTp>
            <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
            <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
            <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
            <pn1:PstCd>pi1:PstCd</pn1:PstCd>
            <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
            <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
            <pn1:Ctry>pi1:Ctry</pn1:Ctry>
          </pn1:PstlAdr>
          <pn1:Id>
            <pn1:OrgId>
              <pn1:BIC>pi1:BIC</pn1:BIC>
              <pn1:IBEI>pi1:IBEI</pn1:IBEI>
              <pn1:BEI>pi1:BEI</pn1:BEI>
              <pn1:EANGLN>pi1:EANGLN</pn1:EANGLN>
              <pn1:USCHU>pi1:USCHU</pn1:USCHU>
              <pn1:DUNS>pi1:DUNS</pn1:DUNS>
              <pn1:BkPtyId>pi1:BkPtyId</pn1:BkPtyId>
              <pn1:TaxIdNb>pi1:TaxIdNb</pn1:TaxIdNb>
              <pn1:PrtryId>
                <pn1:Id>pi1:Id</pn1:Id>
                <pn1:Issr>pi1:Issr</pn1:Issr>
              </pn1:PrtryId>
            </pn1:OrgId>
          </pn1:Id>
          <pn1:CtryOfRes>pi1:CtryOfRes</pn1:CtryOfRes>
        </pn1:UltmtDbtr>
        <pn1:IntrmyAgt1>
          <pn1:FinInstnId>
            <pn1:BIC>pi1:BIC</pn1:BIC>
          </pn1:FinInstnId>
          <pn1:BrnchId>
            <pn1:Id>pi1:Id</pn1:Id>
            <pn1:Nm>pi1:Nm</pn1:Nm>
            <pn1:PstlAdr>
              <pn1:AdrTp>ADDR</pn1:AdrTp>
              <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
              <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
              <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
              <pn1:PstCd>pi1:PstCd</pn1:PstCd>
              <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
              <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
              <pn1:Ctry>pi1:Ctry</pn1:Ctry>
            </pn1:PstlAdr>
          </pn1:BrnchId>
        </pn1:IntrmyAgt1>
        <pn1:IntrmyAgt1Acct>
          <pn1:Id>
            <pn1:IBAN>pi1:IBAN</pn1:IBAN>
          </pn1:Id>
          <pn1:Tp>
            <pn1:Cd>CASH</pn1:Cd>
          </pn1:Tp>
          <pn1:Ccy>pi1:Ccy</pn1:Ccy>
          <pn1:Nm>pi1:Nm</pn1:Nm>
        </pn1:IntrmyAgt1Acct>
        <pn1:IntrmyAgt2>
          <pn1:FinInstnId>
            <pn1:BIC>pi1:BIC</pn1:BIC>
          </pn1:FinInstnId>
          <pn1:BrnchId>
            <pn1:Id>pi1:Id</pn1:Id>
            <pn1:Nm>pi1:Nm</pn1:Nm>
            <pn1:PstlAdr>
              <pn1:AdrTp>ADDR</pn1:AdrTp>
              <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
              <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
              <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
              <pn1:PstCd>pi1:PstCd</pn1:PstCd>
              <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
              <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
              <pn1:Ctry>pi1:Ctry</pn1:Ctry>
            </pn1:PstlAdr>
          </pn1:BrnchId>
        </pn1:IntrmyAgt2>
        <pn1:IntrmyAgt2Acct>
          <pn1:Id>
            <pn1:IBAN>pi1:IBAN</pn1:IBAN>
          </pn1:Id>
          <pn1:Tp>
            <pn1:Cd>CASH</pn1:Cd>
          </pn1:Tp>
          <pn1:Ccy>pi1:Ccy</pn1:Ccy>
          <pn1:Nm>pi1:Nm</pn1:Nm>
        </pn1:IntrmyAgt2Acct>
        <pn1:IntrmyAgt3>
          <pn1:FinInstnId>
            <pn1:BIC>pi1:BIC</pn1:BIC>
          </pn1:FinInstnId>
          <pn1:BrnchId>
            <pn1:Id>pi1:Id</pn1:Id>
            <pn1:Nm>pi1:Nm</pn1:Nm>
            <pn1:PstlAdr>
              <pn1:AdrTp>ADDR</pn1:AdrTp>
              <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
              <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
              <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
              <pn1:PstCd>pi1:PstCd</pn1:PstCd>
              <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
              <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
              <pn1:Ctry>pi1:Ctry</pn1:Ctry>
            </pn1:PstlAdr>
          </pn1:BrnchId>
        </pn1:IntrmyAgt3>
        <pn1:IntrmyAgt3Acct>
          <pn1:Id>
            <pn1:IBAN>pi1:IBAN</pn1:IBAN>
          </pn1:Id>
          <pn1:Tp>
            <pn1:Cd>CASH</pn1:Cd>
          </pn1:Tp>
          <pn1:Ccy>pi1:Ccy</pn1:Ccy>
          <pn1:Nm>pi1:Nm</pn1:Nm>
        </pn1:IntrmyAgt3Acct>
        <pn1:CdtrAgt>
          <pn1:FinInstnId>
            <pn1:BIC>pi1:BIC</pn1:BIC>
          </pn1:FinInstnId>
          <pn1:BrnchId>
            <pn1:Id>pi1:Id</pn1:Id>
            <pn1:Nm>pi1:Nm</pn1:Nm>
            <pn1:PstlAdr>
              <pn1:AdrTp>ADDR</pn1:AdrTp>
              <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
              <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
              <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
              <pn1:PstCd>pi1:PstCd</pn1:PstCd>
              <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
              <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
              <pn1:Ctry>pi1:Ctry</pn1:Ctry>
            </pn1:PstlAdr>
          </pn1:BrnchId>
        </pn1:CdtrAgt>
        <pn1:CdtrAgtAcct>
          <pn1:Id>
            <pn1:IBAN>pi1:IBAN</pn1:IBAN>
          </pn1:Id>
          <pn1:Tp>
            <pn1:Cd>CASH</pn1:Cd>
          </pn1:Tp>
          <pn1:Ccy>pi1:Ccy</pn1:Ccy>
          <pn1:Nm>pi1:Nm</pn1:Nm>
        </pn1:CdtrAgtAcct>
        <pn1:Cdtr>
          <pn1:Nm>pi1:Nm</pn1:Nm>
          <pn1:PstlAdr>
            <pn1:AdrTp>ADDR</pn1:AdrTp>
            <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
            <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
            <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
            <pn1:PstCd>pi1:PstCd</pn1:PstCd>
            <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
            <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
            <pn1:Ctry>pi1:Ctry</pn1:Ctry>
          </pn1:PstlAdr>
          <pn1:Id>
            <pn1:OrgId>
              <pn1:BIC>pi1:BIC</pn1:BIC>
              <pn1:IBEI>pi1:IBEI</pn1:IBEI>
              <pn1:BEI>pi1:BEI</pn1:BEI>
              <pn1:EANGLN>pi1:EANGLN</pn1:EANGLN>
              <pn1:USCHU>pi1:USCHU</pn1:USCHU>
              <pn1:DUNS>pi1:DUNS</pn1:DUNS>
              <pn1:BkPtyId>pi1:BkPtyId</pn1:BkPtyId>
              <pn1:TaxIdNb>pi1:TaxIdNb</pn1:TaxIdNb>
              <pn1:PrtryId>
                <pn1:Id>pi1:Id</pn1:Id>
                <pn1:Issr>pi1:Issr</pn1:Issr>
              </pn1:PrtryId>
            </pn1:OrgId>
          </pn1:Id>
          <pn1:CtryOfRes>pi1:CtryOfRes</pn1:CtryOfRes>
        </pn1:Cdtr>
        <pn1:CdtrAcct>
          <pn1:Id>
            <pn1:IBAN>pi1:IBAN</pn1:IBAN>
          </pn1:Id>
          <pn1:Tp>
            <pn1:Cd>CASH</pn1:Cd>
          </pn1:Tp>
          <pn1:Ccy>pi1:Ccy</pn1:Ccy>
          <pn1:Nm>pi1:Nm</pn1:Nm>
        </pn1:CdtrAcct>
        <pn1:UltmtCdtr>
          <pn1:Nm>pi1:Nm</pn1:Nm>
          <pn1:PstlAdr>
            <pn1:AdrTp>ADDR</pn1:AdrTp>
            <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
            <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
            <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
            <pn1:PstCd>pi1:PstCd</pn1:PstCd>
            <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
            <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
            <pn1:Ctry>pi1:Ctry</pn1:Ctry>
          </pn1:PstlAdr>
          <pn1:Id>
            <pn1:OrgId>
              <pn1:BIC>pi1:BIC</pn1:BIC>
              <pn1:IBEI>pi1:IBEI</pn1:IBEI>
              <pn1:BEI>pi1:BEI</pn1:BEI>
              <pn1:EANGLN>pi1:EANGLN</pn1:EANGLN>
              <pn1:USCHU>pi1:USCHU</pn1:USCHU>
              <pn1:DUNS>pi1:DUNS</pn1:DUNS>
              <pn1:BkPtyId>pi1:BkPtyId</pn1:BkPtyId>
              <pn1:TaxIdNb>pi1:TaxIdNb</pn1:TaxIdNb>
              <pn1:PrtryId>
                <pn1:Id>pi1:Id</pn1:Id>
                <pn1:Issr>pi1:Issr</pn1:Issr>
              </pn1:PrtryId>
            </pn1:OrgId>
          </pn1:Id>
          <pn1:CtryOfRes>pi1:CtryOfRes</pn1:CtryOfRes>
        </pn1:UltmtCdtr>
        <pn1:InstrForCdtrAgt>
          <pn1:Cd>CHQB</pn1:Cd>
          <pn1:InstrInf>pi1:InstrInf</pn1:InstrInf>
        </pn1:InstrForCdtrAgt>
        <pn1:InstrForDbtrAgt>pi1:InstrForDbtrAgt</pn1:InstrForDbtrAgt>
        <pn1:Purp>
          <pn1:Cd>pi1:Cd</pn1:Cd>
        </pn1:Purp>
        <pn1:RgltryRptg>
          <pn1:DbtCdtRptgInd>CRED</pn1:DbtCdtRptgInd>
          <pn1:Authrty>
            <pn1:AuthrtyNm>pi1:AuthrtyNm</pn1:AuthrtyNm>
            <pn1:AuthrtyCtry>pi1:AuthrtyCtry</pn1:AuthrtyCtry>
          </pn1:Authrty>
          <pn1:RgltryDtls>
            <pn1:Cd>pi1:Cd</pn1:Cd>
            <pn1:Amt Ccy="">0.0</pn1:Amt>
            <pn1:Inf>pi1:Inf</pn1:Inf>
          </pn1:RgltryDtls>
        </pn1:RgltryRptg>
        <pn1:Tax>
          <pn1:CdtrTaxId>pi1:CdtrTaxId</pn1:CdtrTaxId>
          <pn1:CdtrTaxTp>pi1:CdtrTaxTp</pn1:CdtrTaxTp>
          <pn1:DbtrTaxId>pi1:DbtrTaxId</pn1:DbtrTaxId>
          <pn1:TaxRefNb>pi1:TaxRefNb</pn1:TaxRefNb>
          <pn1:TtlTaxblBaseAmt Ccy="">0.0</pn1:TtlTaxblBaseAmt>
          <pn1:TtlTaxAmt Ccy="">0.0</pn1:TtlTaxAmt>
          <pn1:TaxDt>2001-01-01</pn1:TaxDt>
          <pn1:TaxTpInf>
            <pn1:CertId>pi1:CertId</pn1:CertId>
            <pn1:TaxTp>
              <pn1:CtgyDesc>pi1:CtgyDesc</pn1:CtgyDesc>
              <pn1:Rate>0.0</pn1:Rate>
              <pn1:TaxblBaseAmt Ccy="">0.0</pn1:TaxblBaseAmt>
              <pn1:Amt Ccy="">0.0</pn1:Amt>
            </pn1:TaxTp>
          </pn1:TaxTpInf>
        </pn1:Tax>
        <pn1:RltdRmtInf>
          <pn1:RmtId>pi1:RmtId</pn1:RmtId>
          <pn1:RmtLctnMtd>FAXI</pn1:RmtLctnMtd>
          <pn1:RmtLctnElctrncAdr>pi1:RmtLctnElctrncAdr</pn1:RmtLctnElctrncAdr>
          <pn1:RmtLctnPstlAdr>
            <pn1:Nm>pi1:Nm</pn1:Nm>
            <pn1:Adr>
              <pn1:AdrTp>ADDR</pn1:AdrTp>
              <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
              <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
              <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
              <pn1:PstCd>pi1:PstCd</pn1:PstCd>
              <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
              <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
              <pn1:Ctry>pi1:Ctry</pn1:Ctry>
            </pn1:Adr>
          </pn1:RmtLctnPstlAdr>
        </pn1:RltdRmtInf>
        <pn1:RmtInf>
          <pn1:Ustrd>pi1:Ustrd</pn1:Ustrd>
          <pn1:Strd>
            <pn1:RfrdDocInf>
              <pn1:RfrdDocTp>
                <pn1:Cd>MSIN</pn1:Cd>
                <pn1:Issr>pi1:Issr</pn1:Issr>
              </pn1:RfrdDocTp>
              <pn1:RfrdDocNb>pi1:RfrdDocNb</pn1:RfrdDocNb>
            </pn1:RfrdDocInf>
            <pn1:RfrdDocRltdDt>2001-01-01</pn1:RfrdDocRltdDt>
            <pn1:RfrdDocAmt>
              <pn1:DuePyblAmt Ccy="">0.0</pn1:DuePyblAmt>
            </pn1:RfrdDocAmt>
            <pn1:CdtrRefInf>
              <pn1:CdtrRefTp>
                <pn1:Cd>RADM</pn1:Cd>
                <pn1:Issr>pi1:Issr</pn1:Issr>
              </pn1:CdtrRefTp>
              <pn1:CdtrRef>pi1:CdtrRef</pn1:CdtrRef>
            </pn1:CdtrRefInf>
            <pn1:Invcr>
              <pn1:Nm>pi1:Nm</pn1:Nm>
              <pn1:PstlAdr>
                <pn1:AdrTp>ADDR</pn1:AdrTp>
                <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
                <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
                <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
                <pn1:PstCd>pi1:PstCd</pn1:PstCd>
                <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
                <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
                <pn1:Ctry>pi1:Ctry</pn1:Ctry>
              </pn1:PstlAdr>
              <pn1:Id>
                <pn1:OrgId>
                  <pn1:BIC>pi1:BIC</pn1:BIC>
                  <pn1:IBEI>pi1:IBEI</pn1:IBEI>
                  <pn1:BEI>pi1:BEI</pn1:BEI>
                  <pn1:EANGLN>pi1:EANGLN</pn1:EANGLN>
                  <pn1:USCHU>pi1:USCHU</pn1:USCHU>
                  <pn1:DUNS>pi1:DUNS</pn1:DUNS>
                  <pn1:BkPtyId>pi1:BkPtyId</pn1:BkPtyId>
                  <pn1:TaxIdNb>pi1:TaxIdNb</pn1:TaxIdNb>
                  <pn1:PrtryId>
                    <pn1:Id>pi1:Id</pn1:Id>
                    <pn1:Issr>pi1:Issr</pn1:Issr>
                  </pn1:PrtryId>
                </pn1:OrgId>
              </pn1:Id>
              <pn1:CtryOfRes>pi1:CtryOfRes</pn1:CtryOfRes>
            </pn1:Invcr>
            <pn1:Invcee>
              <pn1:Nm>pi1:Nm</pn1:Nm>
              <pn1:PstlAdr>
                <pn1:AdrTp>ADDR</pn1:AdrTp>
                <pn1:AdrLine>pi1:AdrLine</pn1:AdrLine>
                <pn1:StrtNm>pi1:StrtNm</pn1:StrtNm>
                <pn1:BldgNb>pi1:BldgNb</pn1:BldgNb>
                <pn1:PstCd>pi1:PstCd</pn1:PstCd>
                <pn1:TwnNm>pi1:TwnNm</pn1:TwnNm>
                <pn1:CtrySubDvsn>pi1:CtrySubDvsn</pn1:CtrySubDvsn>
                <pn1:Ctry>pi1:Ctry</pn1:Ctry>
              </pn1:PstlAdr>
              <pn1:Id>
                <pn1:OrgId>
                  <pn1:BIC>pi1:BIC</pn1:BIC>
                  <pn1:IBEI>pi1:IBEI</pn1:IBEI>
                  <pn1:BEI>pi1:BEI</pn1:BEI>
                  <pn1:EANGLN>pi1:EANGLN</pn1:EANGLN>
                  <pn1:USCHU>pi1:USCHU</pn1:USCHU>
                  <pn1:DUNS>pi1:DUNS</pn1:DUNS>
                  <pn1:BkPtyId>pi1:BkPtyId</pn1:BkPtyId>
                  <pn1:TaxIdNb>pi1:TaxIdNb</pn1:TaxIdNb>
                  <pn1:PrtryId>
                    <pn1:Id>pi1:Id</pn1:Id>
                    <pn1:Issr>pi1:Issr</pn1:Issr>
                  </pn1:PrtryId>
                </pn1:OrgId>
              </pn1:Id>
              <pn1:CtryOfRes>pi1:CtryOfRes</pn1:CtryOfRes>
            </pn1:Invcee>
            <pn1:AddtlRmtInf>pi1:AddtlRmtInf</pn1:AddtlRmtInf>
          </pn1:Strd>
        </pn1:RmtInf>
      </pn1:CdtTrfTxInf>
    </pn1:PmtInf>
  </pn1:pain.001.001.02>
</pn1:Document>